version: "3.1"
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    # TODO: Add 'data' parameter to store db database locally
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: kids-timer
