[package]
name = "kids-timer_admin-api_poc-rust"
version = "0.1.0"
authors = ["Alex Lapinski <contact@alexlapinski.name>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
dotenv = "0.9.0"
diesel = { version = "1.0.0", features = ["postgres"]}