version: "3"
services:
  db:
    image: postgres:alpine
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=admin_user
      - POSTGRES_DB=time_tracker