swagger: "2.0"
info:
  description: "An API to manage time balances for users, and users themselves."
  version: "0.1.0"
  title: "Kid's Timer API"
  contact:
    email: "contact@alexlapinski.name"
host: "localhost"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /user:
    post:
      summary: "Add a new user"
      description: ""
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be added."
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        201:
          description: "Created"
        405:
          description: "Invalid input"
    put:
      summary: "Update an existing pet"
      description: ""
      operationId: "updatePet"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
        405:
          description: "Validation exception"
    get:
      summary: "Get all users"
      description: ""
      operationId: "getUsers"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
        405:
          description: "Invalid input"
  /user/{id}:
    get:
      summary: "Get a user"
      description: ""
      operationId: "getUser"
      parameters:
      - name: id
        in: path
        required: true
        type: integer
        description: "User Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
    delete:
      summary: "Delete a user"
      description: ""
      operationId: "deleteUser"
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          description: "User Id"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "OK"
        405:
          description: "Invalid input"
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
      timeRemaining:
        type: "integer"
        format: "int64"
        description: "Amount of time remaining (in seconds)"